### ISSUE TITLE
How do I change the freeplay checker color?

### ISSUE THREAD

**Issue by JamsTheMans** [LilDrippyMyFnf/FNF-KysikiEngine#3]

**Comment by myffs** [comment]
Well there's 2 ways, one is the source way ( you find MainMenuState.hx and find line 112 ). The second way is simple, change the checkers with any art program you use, just change the colors to anything you want.

**Comment by JamsTheMans** [comment]
thx, also where do i find the assets for the checkers?

**Comment by myffs** [comment]
yw, also go to assets/preload/images/Free_Checkers.png
